# Generated by Django 4.1.7 on 2023-03-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webb", "0002_multipleimage_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MultipleImage",
        ),
    ]
