# Generated by Django 4.1.7 on 2023-03-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("webb", "0003_delete_multipleimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.FileField(upload_to="")),
            ],
        ),
    ]
